/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        bg: "#F5F5F7",
        "bg-subtle": "#FAFAFC",
        surface: "#FFFFFF",
        "surface-subtle": "#F5F5F7",
        "surface-card": "#FFFFFF",
        "surface-border": "rgba(0, 0, 0, 0.08)",
        "surface-border-subtle": "rgba(0, 0, 0, 0.04)",
        "text-primary": "#1D1D1F",
        "text-secondary": "#6E6E73",
        "text-tertiary": "#86868B",
        accent: "#0071E3",
        "accent-hover": "#0077ED",
        "accent-subtle": "rgba(0, 113, 227, 0.08)",
        "apple-blue": "#0071E3",
        "apple-green": "#34C759",
        "apple-orange": "#FF9500",
        "apple-red": "#FF3B30",
        "apple-purple": "#5856D6",
        "risk-critical": "#FF3B30",
        "risk-high": "#FF9500",
        "risk-medium": "#E5A000",
        "risk-low": "#34C759",
      },
      fontFamily: {
        sans: [
          "var(--font-sans)",
          "-apple-system",
          "BlinkMacSystemFont",
          "'SF Pro Display'",
          "'SF Pro Text'",
          "'Inter'",
          "sans-serif",
        ],
        mono: [
          "var(--font-mono)",
          "'SF Mono'",
          "ui-monospace",
          "Menlo",
          "Monaco",
          "Consolas",
          "monospace",
        ],
      },
      letterSpacing: {
        tighter: "-0.04em",
        tight: "-0.03em",
        snug: "-0.015em",
        normal: "-0.01em",
      },
      boxShadow: {
        card: "0 2px 8px rgba(0, 0, 0, 0.04), 0 1px 2px rgba(0, 0, 0, 0.02)",
        "card-hover": "0 12px 28px rgba(0, 0, 0, 0.08), 0 2px 6px rgba(0, 0, 0, 0.03)",
        modal: "0 20px 50px rgba(0, 0, 0, 0.12), 0 4px 12px rgba(0, 0, 0, 0.05)",
        pill: "0 2px 6px rgba(0, 0, 0, 0.06)",
      },
    },
  },
  plugins: [],
};

